ViewColumns = ["TimeGenerated",
               "Name",
               "Properties",
               "ClientType",
               "ClientModel",
               "ClientOS",
               "ClientCity",
               "ClientStateOrProvince",
               "ClientCountryOrRegion",
               "ClientBrowser",
               "SDKVersion"]

FilterColumns = ["Name",
                 "ClientType",
                 "ClientModel",
                 "ClientOS",
                 "ClientCity",
                 "ClientStateOrProvince",
                 "ClientCountryOrRegion",
                 "ClientBrowser"]
